apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "krd-lets-climb-rest.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.pod.service.port }}
      targetPort: {{ .Values.pod.service.targetPort }}
  selector:
    {{- include "krd-lets-climb-rest.selectorLabels" . | nindent 4 }}
  type: {{ .Values.pod.service.type }}