apiVersion: apps/v1
kind: Deployment
metadata:
  name: krd-lets-climb-rest
spec:
  selector:
    replicas: 2
    matchLabels:
      app: krd-lets-climb-rest-app
    revisionHistoryLimit: 2
    template:
      metadata:
        labels:
          app: krd-lets-climb-rest-app
      spec:
        containers:
          - name: krd-lets-climb-rest
            image: kylerobison/krd-lets-climb-rest:1.0.0-SNAPSHOT-3aab34f # Update to make dynamic later
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8080 # The port that the container is running on the cluster