apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
spec:
  selector:
    matchLabels:
      app: APP_NAME
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
    labels:
      app: APP_NAME
    spec:
      containers:
        - name: APP_NAME
          image: FULL_IMAGE_NAME
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      nodeSelector: {}
      affinity: {}
      tolerations: []
